version: '2'

networks:
  test:

services:
  ca_yngadmin:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.yngadmin.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/yngadmin:/etc/hyperledger/fabric-ca-server
    container_name: ca.yngadmin.com
    hostname: ca.yngadmin.com
    networks:
      - test
