Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Dfarmadmin
        Name: DfarmadminMSP
        ID: DfarmadminMSP

        MSPDir: ../../setup1/vm1/crypto-config/peerOrganizations/dfarmadmin.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DfarmadminMSP.admin', 'DfarmadminMSP.peer', 'DfarmadminMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DfarmadminMSP.admin', 'DfarmadminMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DfarmadminMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DfarmadminMSP.peer')"

        AnchorPeers:
            - Host: peer0.dfarmadmin.com
              Port: 7051

    - &Yngadmin
        Name: YngadminMSP

        ID: YngadminMSP

        MSPDir: ../../setup1/vm2/crypto-config/peerOrganizations/yngadmin.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('YngadminMSP.admin', 'YngadminMSP.peer', 'YngadminMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('YngadminMSP.admin', 'YngadminMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('YngadminMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('YngadminMSP.peer')"

        AnchorPeers:
            - Host: peer0.yngadmin.com
              Port: 9051

    - &Dfarmdemo
        Name: DfarmdemoMSP

        ID: DfarmdemoMSP

        MSPDir: ../../setup1/vm3/crypto-config/peerOrganizations/dfarmdemo.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DfarmdemoMSP.admin', 'DfarmdemoMSP.peer', 'DfarmdemoMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DfarmdemoMSP.admin', 'DfarmdemoMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DfarmdemoMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DfarmdemoMSP.peer')"

        AnchorPeers:
            - Host: peer0.dfarmdemo.com
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: dfarmorderer.com
          Port: 7050
          ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/dfarmorderer.com/tls/server.crt
          ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/dfarmorderer.com/tls/server.crt
    Addresses:
        - dfarmorderer.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    yngchannel:
        Consortium: dfarmConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Dfarmadmin
                - *Yngadmin
            Capabilities:
                <<: *ApplicationCapabilities

    demoChannel:
        Consortium: dfarmConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Dfarmadmin
                - *Dfarmdemo
            Capabilities:
                <<: *ApplicationCapabilities
    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: dfarmorderer.com
                  Port: 7050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/dfarmorderer.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/dfarmorderer.com/tls/server.crt
                - Host: orderer2.dfarmorderer.com
                  Port: 8050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/orderer2.dfarmorderer.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/orderer2.dfarmorderer.com/tls/server.crt
                - Host: orderer3.dfarmorderer.com
                  Port: 9050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/orderer3.dfarmorderer.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/dfarmorderer.com/orderers/orderer3.dfarmorderer.com/tls/server.crt
            Addresses:
                - dfarmorderer.com:7050
                - orderer2.dfarmorderer.com:8050
                - orderer3.dfarmorderer.com:9050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            dfarmConsortium:
                Organizations:
                - *Dfarmadmin
                - *Yngadmin
                - *Dfarmdemo
